
import sklearn
print(sklearn.__version__)

import random
def set_FLAGS(Surrogate, Train, Simulate):
        return Surrogate, Train, Simulate

def set_strategy_flags(SO_NORMAL, SO_HHSE, NSGA2_NORMAL, NSGA2_HHSE):
    if SO_NORMAL:
        HHSE, NSGA2 = False, False
    elif SO_HHSE:
        HHSE, NSGA2 = True, False
    elif NSGA2_NORMAL:
        HHSE, NSGA2 = False, True
    elif NSGA2_HHSE:
        HHSE, NSGA2 = True, True
    else:
        HHSE, NSGA2 = None, None
    return HHSE, NSGA2

def list_to_dictionary(list1):
     return {i:value for i,value in enumerate(list1)}

def set_mutation_types_list(REPRESENTATION_TYPE, ENCODING_TYPE):
    if REPRESENTATION_TYPE == 'L': 
        if ENCODING_TYPE == 'INT':
            mutation_types_list = ['MPAR', 'MSWAP', 'NONE'] 
        elif ENCODING_TYPE == 'BIN':
            mutation_types_list = ['MBFLIP', 'NONE']
        elif ENCODING_TYPE == 'REAL':
            mutation_types_list = ['MPOLY', 'MNUF','NONE']
        else:
            mutation_types_list = ['UNKWN ENCODING']
    elif REPRESENTATION_TYPE == 'B': 
        if ENCODING_TYPE == 'INT':
            mutation_types_list = ['MPAR', 'MSWAP', 'NONE']
        elif ENCODING_TYPE == 'BIN':
            mutation_types_list = ['MBFLIP', 'NONE']
        elif ENCODING_TYPE == 'REAL':
            mutation_types_list = ['MPOLY', 'MNUF','NONE']
        else:
            mutation_types_list = ['UNKWN ENCODING']
    else:
        mutation_types_list = ['UNKWN REPRESENTATION_TYPE']
    return mutation_types_list

def set_GREEDY_GOs_list(REPRESENTATION_TYPE, ENCODING_TYPE):
    #For GREEDY SELECTED
    if REPRESENTATION_TYPE == 'B':
        if ENCODING_TYPE == 'REAL':
            GOs_CROSS_stage = ['SPC_MPOLY', 'SPC_MNUF', 'SPC_NONE', 'TPC_MPOLY', 'TPC_MNUF']
            GOs_MUT_stage   = ['SBX_MPOLY', 'SBX_MNUF']
            GOs_HV_stage    = ['SPC_NONE', 'TPC_NONE', 'UC_NONE']
            GOs_GD_stage   = ['SPC_NONE', 'TPC_NONE', 'UC_NONE']
            GOs_ACC_stage  = ...
        else:
            return None, None, None, None
    else:
        return None, None, None, None
    return GOs_CROSS_stage, GOs_MUT_stage, GOs_HV_stage, GOs_GD_stage

def set_GREEDY_FIXED_GOs_list(REPRESENTATION_TYPE, ENCODING_TYPE):
    #['SPC_MPOLY', 'SPC_MNUF', 'SPC_NONE', 'TPC_MPOLY', 'TPC_MNUF', 'TPC_NONE', 'UC_MPOLY', 'UC_MNUF', 'UC_NONE', 'SBX_MPOLY', 'SBX_MNUF', 'SBX_NONE']
    if REPRESENTATION_TYPE == 'B':
        if ENCODING_TYPE == 'REAL': 
            CROSS = ['SBX_MNUF'] #['SBX_MPOLY'] #['SBX_NONE']
            MUT =   ['UC_MNUF'] #['UC_MPOLY']
            HV =    ['SPC_MPOLY'] #['TPC_MPOLY'] #['UC_MPOLY']  #['SBX_MPOLY'] #['NONE_MPOLY']
            DHV =   ['NONE_MNUF'] 
            GD =    ['UC_MPOLY'] #['SBX_MNUF'] #['SBX_NONE'] #['NONE_MNUF'] #['NONE_MPOLY']              
        else:
            return None, None, None, None, None
    else:
        return None, None, None, None, None
    return CROSS, MUT, HV, GD

def set_HHSE_TEC_GOs(REPRESENTATION_TYPE, ENCODING_TYPE):
    if REPRESENTATION_TYPE == 'B':
        if ENCODING_TYPE == 'REAL': 
            #CROSS = {'SPC_MPOLY': 0.45, 'SPC_MNUF': 0.35, 'SPC_NONE': 0.2}
            CROSS = ['SPC_MNUF', 'TPC_MNUF', 'UC_MNUF']
            MUT =   ['SBX_MNUF', 'SBX_MPOLY']
            HV =    ['SPC_MPOLY', 'SBX_NONE', 'TPC_MPOLY']
            #GD =    {'SBX_MNUF':0.30, 'TPC_MNUF': 0.25, 'SPC_MNUF': 0.22, 'UC_MNUF': 0.23}
        else:
            return None, None, None
    else:
        return None, None, None
    return CROSS, MUT, HV

#------------------------------------------------------------- EXPERIMENT SETTINGS ------------------------------------------------------------#

REPRESENTATION_TYPE = 'B'  #L: layer, B: block
ENCODING_TYPE = 'REAL' #INT: integer vector, BIN: binary vector, REAL: real vector (for block representation only)
experiment_folder = 'BLOCKS_70EPOCHS' if REPRESENTATION_TYPE == 'B' else 'LAYERS_20EPOCHS'
REPR_ENC_STR = f'{REPRESENTATION_TYPE}{ENCODING_TYPE}'

search_strategies_list = ['GA', 'RANDOM']
crossover_types_list = ['SPC', 'TPC', 'UC', 'NONE'] if ENCODING_TYPE != 'REAL' else ['SPC', 'TPC', 'UC', 'SBX', 'NONE']
mutation_types_list = set_mutation_types_list(REPRESENTATION_TYPE, ENCODING_TYPE)

#search_strategies_list = ['GA']
#crossover_types_list = ['UC']
#mutation_types_list = ['MPOLY','MNUF', 'NONE']

crossoverList_hhse = crossover_types_list
mutationList_hhse = mutation_types_list


#------------------------------------------------------------- SEARCH STRATEGY ------------------------------------------------------------#
#Single Objective Normal
#Single Objective HHSE
#Multi Objective Normal (with NSGA2)
#Multi Objective HHSE (with NSGA2)
#GREEDY: Apply all GOs, and keep the one according to GREEDY_CRITERIA. For example, if the criteria is CROSS, apply all GOs and keep the population generated by the GO with the highest CROSS.
#        It generates markov matrices.
#GREEDY_CRITERIA: CROSS_SELECTED for example: instead of applying all GOs, it applies only the GOs given by determine_GOs function (which uses set_GREEDY_GOs_list).
#                 COMBINED: uses perc_intervals to apply different stages: CROSS, MUT, HV and GD. It uses all GOs
#                 COMBINED_SELECTED: uses GOs from set_GREEDY_GOs_list for each stage.
# GREEDY_FIXED:  GO is fixed and used to generate population for all generations. The other GOs (from determine_fixed_GOs and set_GREEDY_FIXED_GOs_list) are applied according to the criteria to get stats but they are not used.
# GREEDY_FIXED_RANDOM: Random GOs are applied to generate population for each generation. Still, the other GOs are applied to get stats.
#HHSE_TEC: Not greedy. It should use the best identified GOs for each stage. They must be selected according to some probability (given by the counts).

SO_NORMAL, SO_HHSE, NSGA2_NORMAL, NSGA2_HHSE = (0, 0, 0, 1)
HHSE, NSGA2 = set_strategy_flags(SO_NORMAL, SO_HHSE, NSGA2_NORMAL, NSGA2_HHSE)
NSGA2_WINDOW = 0 if NSGA2_NORMAL else 0
NSGA2_WINDOW_SIZE_PERC = 0.01
HHSE_TEC, HHSE_MARKOV, HHSE_RANDOM, HHSE_GREEDY = (1,0,0,0) if HHSE else (0,0,0,0) 
HHSE_TEC_IMPROVED = False #True: applies GOs depending on stage: MUT, HV, CROSS.

HHSE_GREEDY_FIXED, HHSE_GREEDY_FIXED_RANDOM = (1, 0) if HHSE_GREEDY else (0, 0)
HHSE_GREEDY_CRITERIA = 'CROSS' #'GD', ACC 'HV', 'DHV', 'MUT', 'CROSS', 'CROSS_SELECTED', 'COMBINED', 'COMBINED_SELECTED ----> TO CREATE MARKOV MODELS.
HHSE_MARKOV_TYPES =  ['CROSS', 'MUT', 'HV', 'DHV']#, 'COMBINED'] #Use for single markov runs or combined.
perc_intervals =  [40, 20, 30, 10] #CROSS HV DHV MUT for COMBINED MARKOV

PLOT_PARETO = False
IGNORE_RANDOM = True

if HHSE_GREEDY and HHSE_GREEDY_CRITERIA == 'CROSS':
    crossoverList_hhse = [GO for GO in crossoverList_hhse if GO != 'NONE']
if HHSE_GREEDY and HHSE_GREEDY_CRITERIA == 'MUT':
    mutationList_hhse = [GO for GO in mutationList_hhse if GO != 'NONE']


#------------------------------------------------------------- \SEARCH STRATEGY ------------------------------------------------------------#

INITIAL_SEED = 0
RANDOMIZE_SEED = False

DATASET_PART = 1 #Percentage of the DATASSET as decimal.
MAIN_NPOP = 100#100
EPOCHS = 70 #Number of epochs for training one architecture
GENERATIONS = 500#500
EXECUTIONS = 1 #30 execution is after #GENERATIONS
SEED_LIST = [i for i in range(INITIAL_SEED, INITIAL_SEED + EXECUTIONS)] if RANDOMIZE_SEED == False else random.sample(range(100000), EXECUTIONS)
REGRESSOR_TYPE = 10

SURROGATE, TRAIN, SIMULATE = set_FLAGS(1, 0, 0)


#------------------------------------------------------------- REPORTING ------------------------------------------------------------#
REPORT_ARCH = True #Save arch info in CSV
REPORT_ONLY_BEST = True #Save BEST archs per generation. False saves all archs.
REPORT_ALL_COLUMNS = False #Save full arch info in CSV
RANDOM_NAMES = True #Random names for architecture instead of concatenating parents names.
REPORT_BATCH_SIZE = GENERATIONS #How many archs are saved in the CSV file at once.


#------------------------------------------------------------- REPORTING ------------------------------------------------------------#

PRINT1, PRINT2, PRINT3 = set_FLAGS(1, 0, 0) #Print levels


SORT_IDX = 0
SORT_ARCHS_list = ['SUPERIOR', 'MIDDLE', 'INFERIOR'] #Used for finding best, median or worst archs in a generation
SORT_ARCHS_DICT = list_to_dictionary(SORT_ARCHS_list)
SORT_ARCHS = SORT_ARCHS_DICT[SORT_IDX] 
DATASET_LIST = ['CIFAR10', 'CIFAR100']
DATASET_NUMDENSE_DICT = {'CIFAR10': 10, 'CIFAR100': 100}

plot_archcolumns = ['mean_accuracy','mean_flops', 'mean_params','best_acc', 'FLOPs_bestarch','Params_bestarch']
plot_GAcolumns =  ['HV', 'GD', 'succ_cross', 'succ_mut']
#plot_archcolumns = ['Accuracy', 'FLOPs', 'Num_Params']#, 'Top1', 'Top5']
#plot_archcolumns = ['Accuracy', 'cm_precision_macro', 'cm_recall_macro', 'cm_f1_macro', 'FLOPs', 'Num_Params']#, 'Top1', 'Top5']
#plot_GAcolumns = ['HD_P1', 'HD_P2', 'HD_BM', 'HD_PB', 'Succ_Crossover_ratio', 'Succ_Mutation_ratio', 'NFHT', 'HV', 'GD']
#plot_convergency_columns = ['Accuracy','HD_PB','HV', 'Succ_Crossover_ratio', 'Succ_Mutation_ratio']
plot_convergency_columns = ['Accuracy']
#plot_convergency_generation_status_columns = {'accuracy':['stats', 'max']}#, 'HV':['no_stats', 'max']}
plot_convergency_generation_status_columns = {'mean_accuracy':['stats', 'max'], 'mean_flops':['stats', 'min'], 'mean_params':['stats', 'min'], 
                                              'HV':['no_stats', 'max'], 'dHV':['no_stats', 'max'], 'GD':['no_stats', 'max'], 'succ_cross':['no_stats', 'max'], 'succ_mut':['no_stats', 'max'], 
                                              'best_acc':['no_stats', 'max'], 'FLOPs_bestarch':['no_stats', 'min'], 'Params_bestarch':['no_stats', 'min']}
plot_convergency_generation_status_title_names = {'mean_accuracy':'Mean Pareto Front Accuracy', 'mean_flops':'Mean Pareto Front FLOPs', 'mean_params':'Mean Pareto Front Num_Params', 'HV':'Mean Normalized Hypervolume', 
                                                  'dHV':'Mean Normalized dHV',
                                                  'GD':'Mean Genotypic Distance', 'succ_cross':'Mean Succesful Crossover Ratio', 'succ_mut':'Mean Succesful Mutation Ratio', 
                                                  'best_acc':'Mean Best Accuracy', 'FLOPs_bestarch':'Mean FLOPs from Best Architecture', 'Params_bestarch':'Mean Params from Best Architecture'}
remove_report_columns = ['Epochs', 'Accuracy_history', 'Top1', 'Top5', 'Loss', 'SizeMB', 'Loss_history', 'CPU_Sec', 'P1_idx', 'P2_idx', 'P1', 'P2', 'Search_strategy', 'Chosen_operator', 'Selected_by'] #Discard these columns in report
                              #'Succ_Crossover', 'Succ_Mutation', 'Total_Crossovers', 'Total_Mutations']

#remove_status_columns = ['Generation', 'best_accuracy', 'mean_accuracy', 'mean_dP1', 'mean_dP2', 'mean_dBM', 'dPB',' HV', 'dHV', 'succ_cross', 'succ_mut']                
remove_status_columns = ['Execution', 'Crossover_type', 'Mutation_type', 'Chosen_operator', 'Selected_by', 'GOs_history']


#plot_GA_RANDOM = ['NFHT']
#plot_GA_NONECROSS = ['HD_BM', 'Succ_Mutation_ratio', 'NFHT']
#plot_GA_NONEMUT = plot_GA_RANDOM#['HD_P1', 'HD_P2', 'Succ_Crossover_ratio', 'NFHT']

